<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-12T10:10:44 IST" name="Suite" finished-at="2024-03-12T10:11:59 IST" duration-ms="75273">
    <groups>
    </groups>
    <test started-at="2024-03-12T10:10:44 IST" name="Test3" finished-at="2024-03-12T10:11:59 IST" duration-ms="75273">
      <class name="TestCase.Tc_3HealthInsuranceRunner">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:TestCase.Tc_3HealthInsuranceRunner@139982de]" started-at="2024-03-12T10:10:45 IST" name="setup" finished-at="2024-03-12T10:11:19 IST" duration-ms="34149" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="healthInsurance()[pri:3, instance:TestCase.Tc_3HealthInsuranceRunner@139982de]" started-at="2024-03-12T10:11:19 IST" name="healthInsurance" finished-at="2024-03-12T10:11:26 IST" duration-ms="6396" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at TestCase.Tc_3HealthInsuranceRunner.healthInsurance(Tc_3HealthInsuranceRunner.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- healthInsurance -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCase.Tc_3HealthInsuranceRunner@139982de]" started-at="2024-03-12T10:11:42 IST" name="tearDown" finished-at="2024-03-12T10:11:59 IST" duration-ms="17298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCase.Tc_3HealthInsuranceRunner -->
    </test> <!-- Test3 -->
  </suite> <!-- Suite -->
</testng-results>
